ci(build-check): adding github task with build-check

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -44,3 +44,12 @@ jobs:
 
       - name: Lint
         run: yarn lint
+
+      - name: Build Check
+        run: |
+          if [[ -n $(yarn start && git status -s) ]]; then
+            echo "::error title={Build Check}::{'yarn start' must be ran before committing.}"
+            exit 1
+          else
+            exit 0
+          fi
